- Mac mini M4:
    - Open WebUI:
        href: https://open-webui.k8s.orb.local/
        # container: webui
        # server: macmini-docker
    - Flowise:
        href: https://flowise.k8s.orb.local/
    - Calibre:
        href: https://calibre-web.orb.local/

- Raspberry Pi 4:
    - Home Assistant:
        href: http://raspberrypi-4:8123
        container: homeassistant
        server: rpi4-docker
    - OpenSpeedTest:
        href: http://raspberrypi-4:3000
        container: openspeedtest
        server: rpi4-docker
