version: '3.1'
networks:
  frontend:
    external: true
  iot:
    external: true
services:
  dns:
    # Bind9
    # Referenced from 
    #   - https://www.youtube.com/watch?v=syzwLwE3Xq4&list=PLj-2elZxVPZ8ByT3pEPVFr6MqPH0WsPjc&index=30
    #   - https://hub.docker.com/r/internetsystemsconsortium/bind9
    container_name: dns
    image: ubuntu/bind9:latest
    environment:
      - BIND9_USER=root
      - TZ=Asia/Taipei
    ports:
      - 53:53/udp
      - 53:53/tcp
    volumes:
      - ./configs/bind:/etc/bind
      - ./cache:/var/cache/bind
      - ./records:/var/lib/bind
    restart: unless-stopped

  traefik:
    # Traefik
    # Referenced from https://doc.traefik.io/traefik/getting-started/quick-start/
    container_name: traefik
    image: traefik:v2.10
    ports:
      - 80:80
      - 443:443
      # Enable Dashboard, don't do this in production
      - 8080:8080
    volumes:
      - ./configs/traefik:/etc/traefik
      - ./data/certs:/certs:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - frontend
      - iot
    restart: unless-stopped
  acton-3:
    # Shairport Sync AirPlay receiver
    # Referenced from https://github.com/mikebrady/shairport-sync/blob/master/docker/docker-compose.yaml
    container_name: acton-3
    image: mikebrady/shairport-sync:latest
    command: '--statistics -a "Acton III"'
    restart: unless-stopped
    network_mode: host
    # environment:
    #  PULSE_SERVER: unix:/tmp/pulseaudio.socket # Path for PulseAudio socket
    #  PULSE_COOKIE: /tmp/pulseaudio.cookie # Path for PulseAudio cookie
    devices:
      - "/dev/snd"
    volumes:
      - ./configs/shairport-sync/shairport-sync.conf:/etc/shairport-sync.conf # Customised Shairport Sync configuration file.
    #   - /run/user/1000/pulse/native:/tmp/pulseaudio.socket # PulseAudio socket when using that backend
    logging:
      options:
        max-size: "200k"
        max-file: "10"
  homeassistant:
    # Home Assistant
    # Referenced from https://www.home-assistant.io/installation/raspberrypi#docker-compose
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ./configs/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
  esphome:
    container_name: esphome
    image: esphome/esphome
    volumes:
      - ./configs/esphome/config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    networks:
      - iot
    labels:
      traefik.enable: "true"
      traefik.http.routers.teleport-http.entrypoints: "web"
      traefik.http.routers.teleport-http.rule: "Host(`esphome.rainforest.cluster`)"
      traefik.http.routers.teleport-https.entrypoints: "websecure"
      traefik.http.routers.teleport-https.rule: "Host(`esphome.rainforest.cluster`)"
      traefik.http.routers.teleport-https.tls: "true"

  teleport:
    # Teleport
    # Referenced from https://goteleport.com/docs/installation/#example-of-running-a-teleport-container
    container_name: teleport
    image: public.ecr.aws/gravitational/teleport-distroless-debug:15.0.0
    volumes:
      - ./configs/teleport/config:/etc/teleport
      - ./data/teleport:/var/lib/teleport
    labels:
      traefik.enable: "true"
      traefik.http.services.teleport.loadbalancer.server.port: "3080"
      traefik.http.services.teleport.loadbalancer.server.scheme: "https"
      traefik.http.routers.teleport-http.entrypoints: "web"
      traefik.http.routers.teleport-http.rule: "Host(`teleport.rainforest.cluster`)"
      traefik.http.routers.teleport-https.entrypoints: "websecure"
      traefik.http.routers.teleport-https.rule: "Host(`teleport.rainforest.cluster`)"
      traefik.http.routers.teleport-https.tls: "true"
    networks:
      - frontend
    restart: unless-stopped
